[DataServerInfo]
;==================================================
; Customer Settings
;==================================================
CustomerLicenseId = 0

;==================================================
; Database Settings
;==================================================
DataServerODBC = MuOnline99B
DataServerPort = 55960