[DataServerInfo]
;==================================================
; Customer Settings
;==================================================
CustomerLicenseId = 0

;==================================================
; Database Settings
;==================================================
DataServerODBC = MuOnline
DataServerPort = 55960